In [1]:
import pandas as pd
import numpy as np
# 'Nord-ovest', 'Nord-est', 'Centro', 'Sud', 'Sardegna', 'Sicilia'

def get_Nk_region(region):
    
    # loc region
    df_region = df.loc[(df["Territorio"] == region) & (df["Sesso"] == "totale")]
    group, value = [], []

    group.append("0-9")
    ages = ["Y" + str(i) for i in range(10)]
    value.append(df_region.loc[df_region["ETA1"].isin(ages)]["Value"].sum())

    group.append("10-19")
    ages = ["Y" + str(i) for i in np.arange(10, 20, 1)]
    value.append(df_region.loc[df_region["ETA1"].isin(ages)]["Value"].sum())

    group.append("20-24")
    ages = ["Y" + str(i) for i in np.arange(20, 25, 1)]
    value.append(df_region.loc[df_region["ETA1"].isin(ages)]["Value"].sum())

    group.append("25-29")
    ages = ["Y" + str(i) for i in np.arange(25, 30, 1)]
    value.append(df_region.loc[df_region["ETA1"].isin(ages)]["Value"].sum())

    group.append("30-39")
    ages = ["Y" + str(i) for i in np.arange(30, 40, 1)]
    value.append(df_region.loc[df_region["ETA1"].isin(ages)]["Value"].sum())

    group.append("40-49")
    ages = ["Y" + str(i) for i in np.arange(40, 50, 1)]
    value.append(df_region.loc[df_region["ETA1"].isin(ages)]["Value"].sum())

    group.append("50-59")
    ages = ["Y" + str(i) for i in np.arange(50, 60, 1)]
    value.append(df_region.loc[df_region["ETA1"].isin(ages)]["Value"].sum())

    group.append("60-69")
    ages = ["Y" + str(i) for i in np.arange(60, 70, 1)]
    value.append(df_region.loc[df_region["ETA1"].isin(ages)]["Value"].sum())

    group.append("70-79")
    ages = ["Y" + str(i) for i in np.arange(70, 80, 1)]
    value.append(df_region.loc[df_region["ETA1"].isin(ages)]["Value"].sum())

    group.append("80+")
    ages = ["Y" + str(i) for i in np.arange(80, 100, 1)] + ['Y_GE100']
    value.append(df_region.loc[df_region["ETA1"].isin(ages)]["Value"].sum())

    Nk = pd.DataFrame(data={"group": group, "value": value})
    return Nk


df = pd.read_csv("./DCIS_POPRES1_06052021101115291.csv")
df.head()

,ITTER107,Territorio,TIPO_DATO15,Tipo di indicatore demografico,SEXISTAT1,Sesso,ETA1,Età,STATCIV2,Stato civile,TIME,Seleziona periodo,Value,Flag Codes,Flags
0,IT,Italia,JAN,popolazione al 1º gennaio,1,maschi,Y0,0 anni,99,totale,2021,2021,208698,e,dato stimato
1,IT,Italia,JAN,popolazione al 1º gennaio,2,femmine,Y0,0 anni,99,totale,2021,2021,196623,e,dato stimato
2,IT,Italia,JAN,popolazione al 1º gennaio,9,totale,Y0,0 anni,99,totale,2021,2021,405321,e,dato stimato
3,ITC,Nord-ovest,JAN,popolazione al 1º gennaio,1,maschi,Y0,0 anni,99,totale,2021,2021,54531,e,dato stimato
4,ITC,Nord-ovest,JAN,popolazione al 1º gennaio,2,femmine,Y0,0 anni,99,totale,2021,2021,51577,e,dato stimato

In [2]:
# 'Nord-ovest', 'Nord-est', 'Centro', 'Sud', 'Sardegna', 'Sicilia'

Nk_northwest = get_Nk_region('Nord-ovest')
Nk_northwest.to_csv("../../basins/Italy-northwest/demographic/Nk.csv", index=False)

Nk_northeast = get_Nk_region('Nord-est')
Nk_northeast.to_csv("../../basins/Italy-northeast/demographic/Nk.csv", index=False)

Nk_center = get_Nk_region('Centro')
Nk_center.to_csv("../../basins/Italy-center/demographic/Nk.csv", index=False)

Nk_south = get_Nk_region('Sud')
Nk_south.to_csv("../../basins/Italy-south/demographic/Nk.csv", index=False)

Nk_sicily = get_Nk_region('Sicilia')
Nk_sicily.to_csv("../../basins/Italy-sicily/demographic/Nk.csv", index=False)

Nk_sardinia = get_Nk_region('Sardegna')
Nk_sardinia.to_csv("../../basins/Italy-sardinia/demographic/Nk.csv", index=False)